import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useLanguageStore = defineStore('language', () => {
  const currentLanguage = ref(localStorage.getItem('language') || 'en')
  
  const translations = {
    en: {
      // Dashboard
      financialOverview: 'Financial Overview',
      realTimeSnapshot: 'A real-time snapshot of your financial health.',
      totalBalance: 'Total Balance',
      lastMonth: 'Last month',
      income: 'Income',
      lastPeriod: 'Last Period',
      expenses: 'Expenses',
      net: 'Net',
      netIncomeAfterExpenses: 'Net Income after expenses',
      savings: 'Savings',
      portionOfIncomeRetained: 'Portion of income retained',
      currenciesMarket: 'Currencies Market',
      balanceOverview: 'Balance Overview',
      personalNotes: 'Personal Notes',
      reviewSubscriptions: 'Review subscriptions — Check unlisted subscriptions before the end of the month.',
      recentTransactions: 'Recent Transactions',
      writeJournal: 'Write Journal',
      reviewBudget: 'Review Budget',
      viewReports: 'View Reports',
      activeSubscriptions: 'Active Subscriptions',
      journalEntries: 'Journal Entries',
      viewAll: 'View All',
      noUpcomingSubscriptions: 'No upcoming subscriptions this week.',
      noGoalsYet: 'No goals yet.',
      createGoal: 'Create one!',
      last6Months: 'Last 6 months',
      loadingData: 'Loading your financial data...',
      upcomingSubscriptions: 'Upcoming Subscriptions',
      goalsProgress: 'Goals Progress',


      
      // Sidebar
      menu: 'MENU',
      dashboard: 'Dashboard',
      transactions: 'Transactions',
      budgeting: 'Budgeting',
      goals: 'Goals',
      reports: 'Reports',
      management: 'MANAGEMENT',
      invoices: 'Invoices',
      subscriptions: 'Subscriptions',
      system: 'SYSTEM',
      settings: 'Settings',
      helpSupport: 'Help & Support',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
      logout: 'Logout',
      administrator: 'Administrator',
      
      // Search & Actions
      searchTransactions: 'Search transactions...',
      addTransaction: 'Add Transaction',
      
      // Notifications
      notifications: 'Notifications',
      markAllRead: 'Mark all read',
      noNotifications: 'No notifications',
      
      // Transactions Page
      trackManageTransactions: 'Track and manage all your financial activities',
      totalIncome: 'Total Income',
      totalExpenses: 'Total Expenses',
      netBalance: 'Net Balance',
      transactionsCount: 'Transactions',
      spendingByCategory: 'Spending by Category',
      viewAllCategories: 'View All Categories',
      categoryHealthcare: 'Healthcare',
      categoryEducation: 'Education',
      categoryFitness: 'Fitness',
      categoryProductivity: 'Productivity',
      categoryCloudStorage: 'Cloud Storage',
      categoryMusic: 'Music',
      categoryRent: 'Rent',
      categoryOther: 'Other',
      searchByDescription: 'Search by description...',
      allTypes: 'All Types',
      expense: 'Expense',
      latestFirst: 'Latest First',
      oldestFirst: 'Oldest First',
      highestAmount: 'Highest Amount',
      lowestAmount: 'Lowest Amount',
      loadingTransactions: 'Loading transactions...',
      noTransactionsFound: 'No transactions found',
      noResultsMatchFilters: 'No results match your current filters',
      startTracking: 'Start tracking your finances by adding your first transaction',
      tipIncome: 'Add income: Salary, Freelance, Gifts',
      tipExpenses: 'Add expenses: Food, Transport, Bills',
      tipTrack: 'Track your spending habits over time',
      clearAllFilters: 'Clear All Filters',
      addYourFirstTransaction: 'Add Your First Transaction',
      deleteConfirm: 'Are you sure you want to delete this transaction?',
      delete: 'Delete',
      allCategories: 'All Categories',

      // Budget Page translations 
      budgetUsage: 'Budget Usage',
      budget: 'Budget',
      spent: 'Spent',
      usedFromRegular: 'used from regular spending',
      noBudgetSet: 'No budget set',
      regularSpendingInCategory: 'Regular Spending in this category',
      subscriptionsInCategory: 'Subscriptions in this category',
      nextLabel: 'Next',
      hasSubscription: 'Has Subscription',
      subscriptionSpending: 'Subscription Spending',
      budgetLeft: 'Budget Left',
      totalSpent: 'Total Spent',
      editBudget: 'Edit Budget',
      budgetLimit: 'Budget Limit',
      enterBudgetLimit: 'Enter budget limit',
      save: 'Save',
      cancel: 'Cancel',
      addNewBudgetCategory: 'Add New Budget Category',
      categoryName: 'Category Name',
      categoryPlaceholder: 'e.g., Shopping, Healthcare',
      deleteCategory: 'Delete Category',
      deleteCategoryConfirm: 'Are you sure you want to delete the budget category',
      deleteCategoryWarning: 'This will not delete your past transactions, only the budget limit for this category.',
      budgetUpdated: 'Budget Updated',
      budgetCategoryDeleted: 'Budget Category Deleted',
      newBudgetCategory: 'New Budget Category',
      allSpending: 'All Spending',
      regularSpending: 'Regular Spending',
      totalBudget: 'Total Budget',
      remaining: 'Remaining',
      budgetingDescription: 'Set and manage your spending limits by category',
      addCategory: 'Add Category',
      loadingBudgetData: 'Loading budget data...',
      noBudgetCategoriesYet: 'No Budget Categories Yet',
      noActiveSubscriptionsYet: 'You don\'t have any active subscriptions yet.',
      addFirstBudgetCategory: 'Add your first budget category to start tracking your spending limits',
      addSubscription: 'Add Subscription',
      noSubscriptionsFound: 'No Subscriptions Found',
      
      // Categories
      categoryFood: 'Food',
      categoryTransport: 'Transport',
      categoryEntertainment: 'Entertainment',
      categoryBills: 'Bills',
      categoryHousing: 'Housing',
      categoryUtilities: 'Utilities',
      categoryIncome: 'Income',
      categoryShopping: 'Shopping',
      categoryMaintenance: 'Maintenance',
      categoryDefault: 'Other',
      
      // Goals Page
      loadingGoals: 'Loading goals...',
      trackYourSavings: 'Track your savings goals and watch your progress',
      addNewGoal: 'Add New Goal',
      startSaving: 'Start saving for something special! Add your first financial goal.',
      createFirstGoal: 'Create Your First Goal',
      complete: 'Complete',
      left: 'left',
      achieved: 'Achieved!',
      addProgress: 'Add Progress',
      congratulationsAchieved: 'Congratulations! You\'ve achieved your goal!',
      goalsSummary: 'Goals Summary',
      totalGoals: 'Total Goals',
      goalNamePlaceholder: 'e.g., Emergency Fund, New Laptop, Vacation',
      pleaseEnterGoalName: 'Please enter a goal name',
      pleaseEnterValidTarget: 'Please enter a valid target amount',
      deleteGoalConfirm: 'Are you sure you want to delete this goal?',
      editGoal: 'Edit Goal',
      saveChanges: 'Save Changes',
      createGoal: 'Create Goal',
      goalName: 'Goal Name',
      targetAmount: 'Target Amount',
      savedAmount: 'Saved Amount',
      totalTarget: 'Total Target',
      totalSaved: 'Total Saved',
      overallProgress: 'Overall Progress',
      goalsAchieved: 'Goals Achieved',
      
      // Journal Page
      financialJournal: 'Financial Journal',
      trackYourThoughts: 'Track your thoughts and reflect on your financial journey',
      newEntry: 'New Entry',
      loadingJournalEntries: 'Loading journal entries...',
      noEntriesYet: 'No Journal Entries Yet',
      startWriting: 'Start writing about your financial thoughts, goals, and progress.',
      writeFirstEntry: 'Write Your First Entry',
      journalSummary: 'Journal Summary',
      totalEntries: 'Total Entries',
      mostRecent: 'Most Recent',
      commonMood: 'Common Mood',
      firstEntry: 'First Entry',
      newJournalEntry: 'New Journal Entry',
      journalPlaceholder: 'Write your thoughts about your finances today... How are you feeling about your spending, savings, or financial goals?',
      pleaseWriteEntry: 'Please write something in your journal entry',
      pleaseSelectDate: 'Please select a date',
      deleteEntry: 'Delete this journal entry? This action cannot be undone.',
      dateLabel: 'Date',
      
      // Reports Page
      advancedAnalytics: 'Advanced analytics and insights for your finances',
      howToRead: 'How to read this report',
      budgetHealthDescription: 'Shows how much of your total budget you\'ve used. Above 90% means you\'re close to your limit.',
      subscriptionImpactDescription: 'What percentage of your total expenses go to subscriptions. Helps identify if you\'re overpaying.',
      savingsRateDescription: 'How much of your income you\'re saving. Aim for 20% or more!',
      alertBanners: 'Alert Banners',
      alertBannersDescription: 'Yellow = warning (over 80% used). Red = critical (over 100% used).',
      budgetAlerts: 'Budget Alerts',
      critical: 'critical',
      warning: 'warning',
      timePeriod: 'Time Period',
      selectTimeRange: 'Select a time range to analyze your spending',
      yourTotalBudgetVsActual: 'Your total budget vs actual spending for',
      yourPlannedSpendingLimit: 'Your planned spending limit',
      whatYouveActuallySpent: 'What you\'ve actually spent',
      leftInYourBudget: 'Left in your budget',
      percentageOfBudgetUsed: 'Percentage of budget used',
      overBudget: 'OVER BUDGET!',
      nearLimit: 'Near Limit',
      howCloseYouAre: 'How close you are to exceeding your budget',
      subscriptionImpactDesc: 'How much of your expenses go to subscriptions',
      ofExpenses: 'of Expenses',
      percentageOfIncomeSaving: 'Percentage of income you\'re saving',
      saved: 'Saved',
      savedLabel: 'Saved',
      whereYourMoneyGoes: 'Where your money goes - includes both regular spending and subscriptions',
      hide: 'Hide',
      showDetails: 'Show Details',
      loadingChart: 'Loading chart...',
      yourSpendingPatterns: 'Your spending patterns over time',
      barChart: 'Bar Chart',
      lineChart: 'Line Chart',
      areaChart: 'Area Chart',
      seeSubscriptionImpact: 'See how much you spend on subscriptions vs one-time purchases in each category',
      over: 'over',
      yourBiggestExpenseCategories: 'Your 5 biggest expense categories',
      simpleSuggestions: 'Simple suggestions to improve your finances',
      highSubscriptionMessage: 'You\'re spending',
      ofExpensesOnSubscriptions: 'of your expenses on subscriptions. Consider reviewing unused services.',
      lowSavingsMessage: 'Try to save at least 10-20% of your income. Consider cutting non-essential expenses.',
      negativeSavingsMessage: 'You\'re spending more than you earn! Review your budget and look for areas to reduce spending.',
      budgetAlmostExceededMessage: 'You\'ve used',
      ofYourBudget: 'of your budget. Try to reduce spending in over-budget categories.',
      excellentSavingsMessage: 'You\'re saving',
      ofYourIncome: 'of your income. Keep up the great work!',
      highOneTimeMessage: 'Most of your spending is one-time purchases. Look for subscription alternatives for frequently bought items.',
      noSpendingData: 'No spending data available for the selected period',
      todaysSpendingAlerts: 'Today\'s Spending Alerts',
      spent: 'spent',
      dailyLimit: 'Daily limit',
      
      // Status labels
      active: 'Active',
      paused: 'Paused',
      cancelled: 'Cancelled',

      // Subscriptions page
      monthlySpending: 'Monthly Spending',
      yearlySpending: 'Yearly Spending',
      total: 'Total',
      all: 'All',
      loadingSubscriptions: 'Loading subscriptions...',
      noStatusSubscriptions: 'No',
      subscriptionsFound: 'subscriptions found.',
      addFirstSubscription: 'Add your first subscription to track recurring payments',
      trackManageSubscriptions: 'Track and manage your recurring subscriptions',
      editSubscription: 'Edit Subscription',
      name: 'Name',
      namePlaceholder: 'e.g., Netflix, Spotify',
      amount: 'Amount',
      billingCycle: 'Billing Cycle',
      monthly: 'Monthly',
      yearly: 'Yearly',
      quarterly: 'Quarterly',
      nextBillingDate: 'Next Billing Date',
      budgetLimitPlaceholder: 'Optional - Set budget limit',
      budgetLimitHint: 'Set a budget limit for this category (optional)',
      status: 'Status',
      originalCurrencyNote: 'Original currency',
      subscriptionCreatedInUSD: 'Subscription created in USD. Editing in',
      update: 'Update',
      save: 'Save',
      saving: 'Saving...',
      deleteConfirm: 'Are you sure you want to delete this subscription?',
      monthlyPeriod: 'month',
      yearlyPeriod: 'year',
      quarterlyPeriod: 'quarter',


      // Profile Page
      profileAndSettings: 'Profile & Settings',
      manageAccount: 'Manage your account preferences and personal information',
      userInformation: 'User Information',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      updateProfile: 'Update Profile',
      appearance: 'Appearance',
      dataManagement: 'Data Management',
      exportData: 'Export Data (CSV)',
      deleteAllData: 'Delete All Data',
      currencySettings: 'Currency Settings',
      displayCurrency: 'Display Currency',
      liveExchangeRates: 'Live Exchange Rates',
      systemStatus: 'System Status',
      exchangeRateAPI: 'Exchange Rate API',
      databaseConnection: 'Database Connection',
      connected: 'Connected',
      disconnected: 'Disconnected',
      offline: 'Offline',
      online: 'Online',
      baseCurrency: 'Base Currency',
      lastUpdated: 'Last updated',
      fetchingRates: 'Fetching rates...',
      refreshRates: 'Refresh Rates',
      permanentWarning: 'This action is permanent and cannot be undone!',
      
      // Add Transaction Modal
      addTransactionTitle: 'Add Transaction',
      addTransactionSubtitle: 'Record a new income or expense',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'e.g., Groceries, Salary, Rent',
      amountLabel: 'Amount',
      amountHint: 'Use negative for expenses (-50), positive for income (1000)',
      incomeTypeLabel: 'Income Type',
      incomeTypeHint: 'This helps categorize your income sources',
      salary: 'Salary',
      business: 'Business / Freelance',
      investment: 'Investment / Stocks',
      otherIncome: 'Other Income',
      categoryLabel: 'Category',
      selectCategory: 'Select Category',
      dateLabel: 'Date',
      preview: 'Preview',
      saveTransaction: 'Save Transaction',
      saving: 'Saving...',
      saveSuccess: 'Saved to Supabase!',
      saveFailed: 'Failed to save transaction',
      cancel: 'Cancel'
    },
    ms: {
      // Dashboard
      financialOverview: 'Gambaran Kewangan',
      realTimeSnapshot: 'Gambaran segera kesihatan kewangan anda.',
      totalBalance: 'Jumlah Baki',
      lastMonth: 'Bulan lepas',
      income: 'Pendapatan',
      lastPeriod: 'Tempoh Lepas',
      expenses: 'Perbelanjaan',
      net: 'Bersih',
      netIncomeAfterExpenses: 'Pendapatan Bersih selepas perbelanjaan',
      savings: 'Simpanan',
      portionOfIncomeRetained: 'Bahagian pendapatan yang disimpan',
      currenciesMarket: 'Pasaran Mata Wang',
      balanceOverview: 'Gambaran Baki',
      personalNotes: 'Catatan Peribadi',
      reviewSubscriptions: 'Semak langganan — Periksa langganan sebelum akhir bulan.',
      recentTransactions: 'Transaksi Terkini',
      writeJournal: 'Tulis Jurnal',
      reviewBudget: 'Semak Belanjawan',
      viewReports: 'Lihat Laporan',
      activeSubscriptions: 'Langganan Aktif',
      journalEntries: 'Entri Jurnal',
      viewAll: 'Lihat Semua',
      noUpcomingSubscriptions: 'Tiada langganan akan datang minggu ini.',
      noGoalsYet: 'Tiada matlamat lagi.',
      createGoal: 'Cipta satu!',
      last6Months: '6 Bulan Lepas',
      loadingData: 'Memuatkan data kewangan anda...',
      upcomingSubscriptions: 'Langganan Akan Datang',
      goalsProgress: 'Progres Matlamat',      
      
      // Sidebar
      menu: 'MENU',
      dashboard: 'Papan Pemuka',
      transactions: 'Transaksi',
      budgeting: 'Belanjawan',
      goals: 'Matlamat',
      reports: 'Laporan',
      management: 'PENGURUSAN',
      invoices: 'Invois',
      subscriptions: 'Langganan',
      system: 'SISTEM',
      settings: 'Tetapan',
      helpSupport: 'Bantuan & Sokongan',
      lightMode: 'Mod Terang',
      darkMode: 'Mod Gelap',
      logout: 'Log Keluar',
      administrator: 'Pentadbir',
      
      // Search & Actions
      searchTransactions: 'Cari transaksi...',
      addTransaction: 'Tambah Transaksi',
      
      // Notifications
      notifications: 'Notifikasi',
      markAllRead: 'Tanda semua telah dibaca',
      noNotifications: 'Tiada notifikasi',
      
      // Transactions Page
      trackManageTransactions: 'Jejaki dan urus semua aktiviti kewangan anda',
      totalIncome: 'Jumlah Pendapatan',
      totalExpenses: 'Jumlah Perbelanjaan',
      netBalance: 'Baki Bersih',
      transactionsCount: 'Transaksi',
      spendingByCategory: 'Perbelanjaan mengikut Kategori',
      viewAllCategories: 'Lihat Semua Kategori',
      searchByDescription: 'Cari mengikut keterangan...',
      allTypes: 'Semua Jenis',
      expense: 'Perbelanjaan',
      latestFirst: 'Terbaru Dahulu',
      oldestFirst: 'Terlama Dahulu',
      highestAmount: 'Jumlah Tertinggi',
      lowestAmount: 'Jumlah Terendah',
      loadingTransactions: 'Memuatkan transaksi...',
      noTransactionsFound: 'Tiada transaksi dijumpai',
      noResultsMatchFilters: 'Tiada keputusan yang sepadan dengan penapis anda',
      startTracking: 'Mulakan jejak kewangan anda dengan menambah transaksi pertama',
      tipIncome: 'Tambah pendapatan: Gaji, Freelance, Hadiah',
      tipExpenses: 'Tambah perbelanjaan: Makanan, Pengangkutan, Bil',
      tipTrack: 'Jejaki tabiat perbelanjaan anda dari masa ke masa',
      clearAllFilters: 'Kosongkan Semua Penapis',
      addYourFirstTransaction: 'Tambah Transaksi Pertama Anda',
      deleteConfirm: 'Adakah anda pasti mahu memadamkan transaksi ini?',
      delete: 'Padam',
      allCategories: 'Semua Kategori',

      // Budget Page translations - add under the existing entries
      budgetUsage: 'Penggunaan Belanjawan',
      budget: 'Belanjawan',
      spent: 'Dibelanjakan',
      usedFromRegular: 'digunakan dari perbelanjaan biasa',
      noBudgetSet: 'Tiada belanjawan ditetapkan',
      regularSpendingInCategory: 'Perbelanjaan Biasa dalam kategori ini',
      subscriptionsInCategory: 'Langganan dalam kategori ini',
      budgetHealthTitle: 'Kesihatan Belanjawan',
      subscriptionImpactTitle: 'Kesan Langganan',
      savingsRateTitle: 'Kadar Simpanan',
      alertBannersTitle: 'Banner Amaran',
      howToRead: 'Cara membaca laporan ini',
      nextLabel: 'Seterusnya',
      hasSubscription: 'Mempunyai Langganan',
      subscriptionSpending: 'Perbelanjaan Langganan',
      budgetLeft: 'Baki Belanjawan',
      totalSpent: 'Jumlah Dibelanjakan',
      editBudget: 'Edit Belanjawan',
      budgetLimit: 'Had Belanjawan',
      enterBudgetLimit: 'Masukkan had belanjawan',
      save: 'Simpan',
      cancel: 'Batal',
      addNewBudgetCategory: 'Tambah Kategori Belanjawan Baru',
      categoryName: 'Nama Kategori',
      categoryPlaceholder: 'Cth: Membeli-belah, Penjagaan Kesihatan',
      deleteCategory: 'Padam Kategori',
      deleteCategoryConfirm: 'Adakah anda pasti mahu memadamkan kategori belanjawan',
      deleteCategoryWarning: 'Ini tidak akan memadamkan transaksi lepas anda, hanya had belanjawan untuk kategori ini.',
      budgetUpdated: 'Belanjawan Dikemaskini',
      budgetCategoryDeleted: 'Kategori Belanjawan Dipadam',
      newBudgetCategory: 'Kategori Belanjawan Baru',
      allSpending: 'Semua Perbelanjaan',
      regularSpending: 'Perbelanjaan Biasa',
      totalBudget: 'Jumlah Belanjawan',
      remaining: 'Baki',
      budgetingDescription: 'Tetapkan dan uruskan had perbelanjaan anda mengikut kategori',
      addCategory: 'Tambah Kategori',
      loadingBudgetData: 'Memuatkan data belanjawan...',
      noBudgetCategoriesYet: 'Tiada Kategori Belanjawan Lagi',
      noActiveSubscriptionsYet: 'Anda tidak mempunyai sebarang langganan aktif lagi.',
      addFirstBudgetCategory: 'Tambah kategori belanjawan pertama anda untuk mula menjejak had perbelanjaan anda',
      addSubscription: 'Tambah Langganan',
      noSubscriptionsFound: 'Tiada Langganan Dijumpai',
      
      // Categories
      categoryFood: 'Makanan',
      categoryTransport: 'Pengangkutan',
      categoryEntertainment: 'Hiburan',
      categoryBills: 'Bil',
      categoryHousing: 'Perumahan',
      categoryUtilities: 'Utiliti',
      categoryIncome: 'Pendapatan',
      categoryShopping: 'Membeli-belah',
      categoryMaintenance: 'Penyelenggaraan',
      categoryHealthcare: 'Penjagaan Kesihatan',
      categoryEducation: 'Pendidikan',
      categoryFitness: 'Kecergasan',
      categoryProductivity: 'Produktiviti',
      categoryCloudStorage: 'Penyimpanan Awan',
      categoryMusic: 'Muzik',
      categoryRent: 'Sewa',
      categoryDefault: 'Lain-lain',

      
      // Goals Page
      loadingGoals: 'Memuatkan matlamat...',
      trackYourSavings: 'Jejaki matlamat simpanan anda dan lihat kemajuan',
      addNewGoal: 'Tambah Matlamat Baru',
      startSaving: 'Mulakan simpanan untuk sesuatu yang istimewa! Tambah matlamat kewangan pertama anda.',
      createFirstGoal: 'Cipta Matlamat Pertama Anda',
      complete: 'Selesai',
      left: 'lagi',
      achieved: 'Tercapai!',
      addProgress: 'Tambah Kemajuan',
      congratulationsAchieved: 'Tahniah! Anda telah mencapai matlamat anda!',
      goalsSummary: 'Ringkasan Matlamat',
      totalGoals: 'Jumlah Matlamat',
      goalNamePlaceholder: 'Cth: Dana Kecemasan, Komputer Riba, Percutian',
      pleaseEnterGoalName: 'Sila masukkan nama matlamat',
      pleaseEnterValidTarget: 'Sila masukkan jumlah sasaran yang sah',
      deleteGoalConfirm: 'Adakah anda pasti mahu memadamkan matlamat ini?',
      editGoal: 'Edit Matlamat',
      saveChanges: 'Simpan Perubahan',
      createGoal: 'Cipta Matlamat',
      goalName: 'Nama Matlamat',
      targetAmount: 'Jumlah Sasaran',
      savedAmount: 'Jumlah Disimpan',
      totalTarget: 'Jumlah Sasaran',
      totalSaved: 'Jumlah Disimpan',
      overallProgress: 'Kemajuan Keseluruhan',
      goalsAchieved: 'Matlamat Tercapai',

      
      // Journal Page
      financialJournal: 'Jurnal Kewangan',
      trackYourThoughts: 'Jejaki pemikiran anda dan renungkan perjalanan kewangan anda',
      newEntry: 'Entri Baru',
      loadingJournalEntries: 'Memuatkan entri jurnal...',
      noEntriesYet: 'Tiada Entri Jurnal Lagi',
      startWriting: 'Mulakan menulis tentang pemikiran, matlamat, dan kemajuan kewangan anda.',
      writeFirstEntry: 'Tulis Entri Pertama Anda',
      journalSummary: 'Ringkasan Jurnal',
      totalEntries: 'Jumlah Entri',
      mostRecent: 'Terbaru',
      commonMood: 'Perasaan Biasa',
      firstEntry: 'Entri Pertama',
      newJournalEntry: 'Entri Jurnal Baru',
      journalPlaceholder: 'Tulis pemikiran anda tentang kewangan hari ini... Bagaimana perasaan anda tentang perbelanjaan, simpanan, atau matlamat kewangan anda?',
      pleaseWriteEntry: 'Sila tulis sesuatu dalam entri jurnal anda',
      pleaseSelectDate: 'Sila pilih tarikh',
      deleteEntry: 'Padam entri jurnal ini? Tindakan ini tidak boleh dibatalkan.',
      dateLabel: 'Tarikh',
      
      // Reports Page
      advancedAnalytics: 'Analisis lanjutan dan cerapan untuk kewangan anda',
      howToRead: 'Cara membaca laporan ini',
      budgetHealthDescription: 'Menunjukkan berapa banyak jumlah belanjawan yang telah digunakan. Melebihi 90% bermakna anda hampir mencapai had.',
      subscriptionImpactDescription: 'Peratusan perbelanjaan total anda untuk langganan. Membantu mengenal pasti jika anda membayar lebih.',
      savingsRateDescription: 'Berapa banyak pendapatan yang anda simpan. Sasarkan 20% atau lebih!',
      alertBanners: 'Banner Amaran',
      alertBannersDescription: 'Kuning = amaran (lebih 80% digunakan). Merah = kritikal (lebih 100% digunakan).',
      budgetAlerts: 'Amaran Belanjawan',
      critical: 'kritikal',
      warning: 'amaran',
      timePeriod: 'Tempoh Masa',
      selectTimeRange: 'Pilih julat masa untuk menganalisis perbelanjaan anda',
      yourTotalBudgetVsActual: 'Jumlah belanjawan vs perbelanjaan sebenar untuk',
      yourPlannedSpendingLimit: 'Had perbelanjaan yang dirancang',
      whatYouveActuallySpent: 'Apa yang sebenarnya telah dibelanjakan',
      leftInYourBudget: 'Baki dalam belanjawan anda',
      percentageOfBudgetUsed: 'Peratusan belanjawan digunakan',
      overBudget: 'MELEBIHI BELANJAWAN!',
      nearLimit: 'Hampir Had',
      howCloseYouAre: 'Sejauh mana anda hampir melebihi belanjawan',
      subscriptionImpactDesc: 'Berapa banyak perbelanjaan anda untuk langganan',
      ofExpenses: 'dari Perbelanjaan',
      percentageOfIncomeSaving: 'Peratusan pendapatan yang anda simpan',
      saved: 'Disimpan',
      savedLabel: 'Disimpan',
      whereYourMoneyGoes: 'Di mana wang anda pergi - termasuk perbelanjaan biasa dan langganan',
      hide: 'Sembunyi',
      showDetails: 'Tunjukkan Butiran',
      loadingChart: 'Memuatkan carta...',
      yourSpendingPatterns: 'Corak perbelanjaan anda dari masa ke masa',
      barChart: 'Carta Bar',
      lineChart: 'Carta Garis',
      areaChart: 'Carta Kawasan',
      seeSubscriptionImpact: 'Lihat berapa banyak anda berbelanja untuk langganan vs pembelian sekali dalam setiap kategori',
      over: 'lebih',
      yourBiggestExpenseCategories: '5 kategori perbelanjaan terbesar anda',
      simpleSuggestions: 'Cadangan mudah untuk menambah baik kewangan anda',
      highSubscriptionMessage: 'Anda membelanjakan',
      ofExpensesOnSubscriptions: 'daripada perbelanjaan anda untuk langganan. Pertimbangkan untuk menyemak perkhidmatan yang tidak digunakan.',
      lowSavingsMessage: 'Cuba simpan sekurang-kurangnya 10-20% daripada pendapatan anda. Pertimbangkan untuk mengurangkan perbelanjaan tidak penting.',
      negativeSavingsMessage: 'Anda membelanjakan lebih daripada pendapatan! Semak belanjawan anda dan cari kawasan untuk mengurangkan perbelanjaan.',
      budgetAlmostExceededMessage: 'Anda telah menggunakan',
      ofYourBudget: 'daripada belanjawan anda. Cuba kurangkan perbelanjaan dalam kategori yang melebihi bajet.',
      excellentSavingsMessage: 'Anda menyimpan',
      ofYourIncome: 'daripada pendapatan anda. Teruskan usaha yang baik!',
      highOneTimeMessage: 'Kebanyakan perbelanjaan anda adalah pembelian sekali. Cari alternatif langganan untuk barangan yang kerap dibeli.',
      noSpendingData: 'Tiada data perbelanjaan untuk tempoh yang dipilih',
      todaysSpendingAlerts: 'Amaran Perbelanjaan Hari Ini',
      spent: 'dibelanjakan',
      dailyLimit: 'Had harian',
      monthlyPeriod: 'bulan',
      yearlyPeriod: 'tahun',
      quarterlyPeriod: 'suku',

      // Status labels
      active: 'Aktif',
      paused: 'Ditunda',
      cancelled: 'Dibatalkan',
      monthly: 'Bulanan',
      yearly: 'Tahunan',
      quarterly: 'Suku Tahun',

      // Subscriptions page
      monthlySpending: 'Perbelanjaan Bulanan',
      yearlySpending: 'Perbelanjaan Tahunan',
      total: 'Jumlah',
      all: 'Semua',
      loadingSubscriptions: 'Memuatkan langganan...',
      noStatusSubscriptions: 'Tiada',
      subscriptionsFound: 'langganan dijumpai.',
      addFirstSubscription: 'Tambah langganan pertama anda untuk menjejak pembayaran berulang',
      trackManageSubscriptions: 'Jejaki dan urus langganan berulang anda',
      editSubscription: 'Edit Langganan',
      name: 'Nama',
      namePlaceholder: 'Cth: Netflix, Spotify',
      amount: 'Jumlah',
      billingCycle: 'Kitaran Bil',
      monthly: 'Bulanan',
      yearly: 'Tahunan',
      quarterly: 'Suku Tahun',
      nextBillingDate: 'Tarikh Bil Seterusnya',
      budgetLimitPlaceholder: 'Pilihan - Tetapkan had belanjawan',
      budgetLimitHint: 'Tetapkan had belanjawan untuk kategori ini (pilihan)',
      status: 'Status',
      originalCurrencyNote: 'Mata wang asal',
      subscriptionCreatedInUSD: 'Langganan dicipta dalam USD. Mengedit dalam',
      update: 'Kemaskini',
      save: 'Simpan',
      saving: 'Menyimpan...',
      deleteConfirm: 'Adakah anda pasti mahu memadamkan langganan ini?',

      // Profile Page
      profileAndSettings: 'Profil & Tetapan',
      manageAccount: 'Urus keutamaan akaun dan maklumat peribadi anda',
      userInformation: 'Maklumat Pengguna',
      fullName: 'Nama Penuh',
      emailAddress: 'Alamat E-mel',
      updateProfile: 'Kemaskini Profil',
      appearance: 'Penampilan',
      dataManagement: 'Pengurusan Data',
      exportData: 'Eksport Data (CSV)',
      deleteAllData: 'Padam Semua Data',
      currencySettings: 'Tetapan Mata Wang',
      displayCurrency: 'Mata Wang Paparan',
      liveExchangeRates: 'Kadar Pertukaran Langsung',
      systemStatus: 'Status Sistem',
      exchangeRateAPI: 'API Kadar Pertukaran',
      databaseConnection: 'Sambungan Pangkalan Data',
      connected: 'Bersambung',
      disconnected: 'Terputus',
      offline: 'Luar Talian',
      online: 'Dalam Talian',
      baseCurrency: 'Mata Wang Asas',
      lastUpdated: 'Kemaskini terakhir',
      fetchingRates: 'Mengambil kadar...',
      refreshRates: 'Segarkan Kadar',
      permanentWarning: 'Tindakan ini kekal dan tidak boleh dibatalkan!',
      
      // Add Transaction Modal
      addTransactionTitle: 'Tambah Transaksi',
      addTransactionSubtitle: 'Rekod pendapatan atau perbelanjaan baharu',
      descriptionLabel: 'Keterangan',
      descriptionPlaceholder: 'Contoh: Barangan runcit, Gaji, Sewa',
      amountLabel: 'Jumlah',
      amountHint: 'Gunakan negatif untuk perbelanjaan (-50), positif untuk pendapatan (1000)',
      incomeTypeLabel: 'Jenis Pendapatan',
      incomeTypeHint: 'Ini membantu mengkategorikan sumber pendapatan anda',
      salary: 'Gaji',
      business: 'Perniagaan / Freelance',
      investment: 'Pelaburan / Saham',
      otherIncome: 'Pendapatan Lain',
      categoryLabel: 'Kategori',
      selectCategory: 'Pilih Kategori',
      dateLabel: 'Tarikh',
      preview: 'Pratonton',
      saveTransaction: 'Simpan Transaksi',
      saving: 'Menyimpan...',
      saveSuccess: 'Disimpan ke Supabase!',
      saveFailed: 'Gagal menyimpan transaksi',
      cancel: 'Batal'
    }
  }
  
  function setLanguage(lang) {
    currentLanguage.value = lang
    localStorage.setItem('language', lang)
  }
  
  const t = computed(() => translations[currentLanguage.value])
  
  // Helper function to translate category names
  function translateCategory(category) {
  const categoryMap = {
    // English to Malay mappings
    'Food': t.value.categoryFood,
    'Transport': t.value.categoryTransport,
    'Entertainment': t.value.categoryEntertainment,
    'Bills': t.value.categoryBills,
    'Housing': t.value.categoryHousing,
    'Utilities': t.value.categoryUtilities,
    'Income': t.value.categoryIncome,
    'Shopping': t.value.categoryShopping,
    'Maintenance': t.value.categoryMaintenance,
    'Healthcare': t.value.categoryHealthcare || 'Penjagaan Kesihatan',
    'Education': t.value.categoryEducation || 'Pendidikan',
    'Fitness': t.value.categoryFitness || 'Kecergasan',
    'Productivity': t.value.categoryProductivity || 'Produktiviti',
    'Cloud Storage': t.value.categoryCloudStorage || 'Penyimpanan Awan',
    'Music': t.value.categoryMusic || 'Muzik',
    'Rent': t.value.categoryRent || 'Sewa',
    'Other': t.value.categoryOther || 'Lain-lain'
  }
  return categoryMap[category] || category || t.value.categoryDefault
}

  
  return {
    currentLanguage,
    t,
    setLanguage,
    translateCategory
  }
})